In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset = pd.read_csv(r"C:\Users\ASUS\Documents\DataIpk.csv")
X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[ 3. 14.  4.]
 [ 2. 56.  5.]
 [ 3. 56.  7.]
 [ 3.  8.  6.]
 [ 3.  5. nan]]


In [5]:
print(Y)

['Yes;;;;;' 'No;;;;;' 'No;;;;;' 'Yes;;;;;' 'No;;;;;']


In [6]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])
print(X)

[[ 3.  14.   4. ]
 [ 2.  56.   5. ]
 [ 3.  56.   7. ]
 [ 3.   8.   6. ]
 [ 3.   5.   5.5]]


In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers =[('encoder',OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [8]:
print(X)

[[ 0.   1.  14.   4. ]
 [ 1.   0.  56.   5. ]
 [ 0.   1.  56.   7. ]
 [ 0.   1.   8.   6. ]
 [ 0.   1.   5.   5.5]]


In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(Y)
print(y)

[1 0 0 1 0]


In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size = 0.2, random_state = 1)
print(X_train)

[[ 1.   0.  56.   5. ]
 [ 0.   1.   5.   5.5]
 [ 0.   1.  14.   4. ]
 [ 0.   1.   8.   6. ]]


In [11]:
print(X_test)

[[ 0.  1. 56.  7.]]


In [12]:
print(y_train)

['No;;;;;' 'No;;;;;' 'Yes;;;;;' 'Yes;;;;;']


In [13]:
print(y_test)

['No;;;;;']


In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [15]:
print(X_train)

[[ 1.          0.         56.         -0.16903085]
 [ 0.          1.          5.          0.50709255]
 [ 0.          1.         14.         -1.52127766]
 [ 0.          1.          8.          1.18321596]]


In [16]:
print(X_test)

[[ 0.          1.         56.          2.53546276]]
