In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset = pd.read_csv(r"C:\Users\ASUS\Documents\DataNilai.csv")
X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, -1].values

In [4]:
print(X)

[['Adi' 75 4.0]
 ['Bejo' 65 5.0]
 ['Aini' 84 7.0]
 ['Nana' 90 6.0]
 ['Ian' 87 nan]]


In [5]:
print(Y)

['Yes' 'No' 'No' 'Yes' 'No']


In [6]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])
print(X)

[['Adi' 75.0 4.0]
 ['Bejo' 65.0 5.0]
 ['Aini' 84.0 7.0]
 ['Nana' 90.0 6.0]
 ['Ian' 87.0 5.5]]


In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers =[('encoder',OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [8]:
print(X)

[[1.0 0.0 0.0 0.0 0.0 75.0 4.0]
 [0.0 0.0 1.0 0.0 0.0 65.0 5.0]
 [0.0 1.0 0.0 0.0 0.0 84.0 7.0]
 [0.0 0.0 0.0 0.0 1.0 90.0 6.0]
 [0.0 0.0 0.0 1.0 0.0 87.0 5.5]]


In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(Y)
print(y)

[1 0 0 1 0]


In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size = 0.2, random_state = 1)
print(X_train)

[[0.0 0.0 1.0 0.0 0.0 65.0 5.0]
 [0.0 0.0 0.0 1.0 0.0 87.0 5.5]
 [1.0 0.0 0.0 0.0 0.0 75.0 4.0]
 [0.0 0.0 0.0 0.0 1.0 90.0 6.0]]


In [11]:
print(X_test)

[[0.0 1.0 0.0 0.0 0.0 84.0 7.0]]


In [12]:
print(y_train)

['No' 'No' 'Yes' 'Yes']


In [13]:
print(y_test)

['No']


In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [15]:
print(X_train)

[[0.0 0.0 1.0 -0.5773502691896258 -0.5773502691896258 -1.430824580165594
  -0.1690308509457033]
 [0.0 0.0 0.0 1.7320508075688774 -0.5773502691896258 0.7781677541251477
  0.50709255283711]
 [1.0 0.0 0.0 -0.5773502691896258 -0.5773502691896258
  -0.42673715548798424 -1.52127765851133]
 [0.0 0.0 0.0 -0.5773502691896258 1.7320508075688774 1.0793939815284306
  1.1832159566199232]]


In [16]:
print(X_test)

[[0.0 1.0 0.0 -0.5773502691896258 -0.5773502691896258 0.47694152672186474
  2.53546276418555]]
